client_secret: osskNrpccqcVLHbR0DaQdi2HHwcyNvtD
debug: false
disable_auto_update: true
disable_command_execute: false
disable_force_update: true
disable_nat: false
disable_send_query: false
gpu: false
insecure_tls: false
ip_report_period: 1800
report_delay: 1
server: hxomfbhtwnua.ap-southeast-1.clawcloudrun.com:443
skip_connection_count: false
skip_procs_count: false
temperature: false
tls: true
use_gitee_to_upgrade: false
use_ipv6_country_code: false
uuid: c78c9984-fe96-4f66-869b-7c0bf5c4232f
